### ISSUE TITLE
"Fields are empty" error message would not show

### ISSUE THREAD

**Issue by ekhattar** [gabriela99/capstone-code#3]
With the order of the conditions, the statement to handle when both the email & password are empty would never be reached. This is because if both are empty, then the first condition (email empty) is always true.

https://github.com/gabriela99/capstone-code/blob/76a98694dcf14ea4b4b2f6d04657c05a055fa5f3/app/src/main/java/com/example/capstone_code/MainActivity.java#L68

**Comment by gabriela99** [comment]
Removed this redundant condition.
