### ISSUE TITLE
Editing the user profile: show autocomplete suggestions when field empty

### ISSUE THREAD

**Issue by ekhattar** [gabriela99/capstone-code#5]
## Description

Right now in the `autoCompleteText()` function in `SettingsActivity.Java`, we have the following code

https://github.com/gabriela99/capstone-code/blob/b33ae0e043e07da79513359108b3aa90835e7a7e/app/src/main/java/com/example/capstone_code/SettingsActivity.java#L149-L150

This implies that a user should input 0 characters (empty field) and all autocomplete suggestions should be shown.

However, the documentation for `setThreshold` says the following:

> When threshold is less than or equals 0, a threshold of 1 is applied.

http://developer.android.com/intl/de/reference/android/widget/AutoCompleteTextView.html#setThreshold%28int%29

This means that the user **always has to type at least 1 character** to see the options.

This is why currently, the autocomplete suggestion dropdown for "role" and "skills" is **not shown** unless a user inputs 1 character minimum (despite the threshold set to 0).

Instead, the options should be shown in two cases:
1. When the field is first clicked (focused on)
2. When the field is empty (e.g., user typed "a" but then hit backspace)

### Case 1: Initial Focus

For case 1, you can use a `OnFocusChangeListener()` to check when the input field becomes focused (user clicks on "role"):

https://developer.android.com/reference/android/view/View.OnFocusChangeListener

The dropdown options of an autocomplete can be shown by calling `acTextViewRoles.showDropDown()` (`showDropdown()` method of any auto complete)

```java
        // When the user first focuses on the field, show all options
        acTextViewRoles.setOnFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View textView, boolean hasFocus) {
                // If the view is focused, show the dropdown
                if(hasFocus){
                    acTextViewRoles.showDropDown();
                }
            }
        });
```

This should be done after the autocomplete is populated with the adapter, i.e., after the following in the `autoCompleteText()` function

https://github.com/gabriela99/capstone-code/blob/b33ae0e043e07da79513359108b3aa90835e7a7e/app/src/main/java/com/example/capstone_code/SettingsActivity.java#L152-L153

### Case 2: Empty Field After Backspace

For case 2, a user would enter some text "Agi..." and then press backspace until the input field is empty, i.e., `""`

In this case, again all options should be shown

One **possible** way to do this is using `TextWatcher` which is a text change listener:
https://developer.android.com/reference/android/text/TextWatcher

In the following example, a `TextWatcher` listener is added to the autocomplete text view.

```java
        acTextViewRoles.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start,
                                          int count, int after) {
            }
            @Override
            public void onTextChanged(CharSequence s, int start,
                                      int before, int count) {
            }
            @Override
            public void afterTextChanged (android.text.Editable s) {
                // After the text is done changing, check the value of the text view
                // If the length of the string equals 0 (so an empty input), call
               // again the showDropdown() function
                if(acTextViewRoles.getText().toString().length() == 0){
                    acTextViewRoles.showDropDown();
                }
            }
        });
```

To use the `TextWatcher`, you have to override three methods: `beforeTextChanged`, `onTextChanged`, and `afterTextChanged`

⚠️  **HOWEVER**, in the above example if you implement it exactly the same way, right now the dropdown (autocomplete options) **shows only for a second before disappearing**.

Therefore, this can be handled 2 ways:

1. Debug why the dropdown options disappear (maybe a timing or event problem?)
2. Look into other event listeners that could be used

**Comment by ekhattar** [comment]
## Update 22.10

After briefly looking into it, the solution above does work with a delay

Basically what's happening is the following:

1. User types text `"Pro"`
2. Dropdown shows `"Product manager"`
3. User presses backspace until the input field is empty `""`
4. This triggers the text change listener set on the autocomplete field `TextWatcher()`
5. Text watcher's `afterTextChanged()` function checks if the input field is empty `""` (length 0)
6. If this condition is met (so input is empty)...
   - then we set a 100 millisec delay before executing ....
   - `acTextViewRoles.showDropDown()` (same as in the focus change listener)
   - this triggers the dropdown to show on the autocomplete field

As for the **why** this tiny delay is necessary, I got the idea after observing the behavior in the description code. Because the dropdown shows for a brief second before disappearing, it looks like something within the array adapter or autocomplete implementation triggers another event after (for example, looking for an autocomplete suggestion that matches `""` as that is the input), which hides the dropdown (which could be showing but with no matching options). 
Because of this, setting the delay helps check show the dropdown at some point when all of autocomplete / array adapter's other conditions and triggers are done. 

- Delay handler documentation: https://developer.android.com/reference/android/os/Handler

See comments in code below for more details

```java
    private void autoCompleteText(String[] listOptions, EditText mField) {
        //Create the instance of ArrayAdapter containing list of roles
        ArrayAdapter<String> adapterRoles = new ArrayAdapter<>(this,android.R.layout.select_dialog_singlechoice, listOptions);

        //Find TextView control
        final AutoCompleteTextView acTextViewRoles = (AutoCompleteTextView) mField;

        // Set the number of characters the user must type before the drop down list is shown
        acTextViewRoles.setThreshold(1);

        //Set the adapter
        acTextViewRoles.setAdapter(adapterRoles);

        // When the user first focuses on the field, show all options
        acTextViewRoles.setOnFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View textView, boolean hasFocus) {
                // If the view is focused, show the dropdown
                if(hasFocus){
                    acTextViewRoles.showDropDown();
                }
            }
        });

        acTextViewRoles.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start,
                                          int count, int after) {
            }
            @Override
            public void onTextChanged(CharSequence s, int start,
                                      int before, int count) {
            }
            @Override
            public void afterTextChanged (android.text.Editable s) {
                // After the text is done changing, check the value of the text view
                // If the length of the string equals 0 (so an empty input), call
                // again the showDropdown() function
                if(acTextViewRoles.getText().toString().length() == 0){
                    // Handler to run after delay https://developer.android.com/reference/android/os/Handler
                    final Handler handler = new Handler();
                    // Waits 100 millisec before executing showDropDown()
                    handler.postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            acTextViewRoles.showDropDown();
                        }
                    }, 100);

                }
            }
        });
    }
```

**Comment by gabriela99** [comment]
Works great, I implemented it and pushed it.
