### ISSUE TITLE
Editing user profile: new changes don't take into effect immediately

### ISSUE THREAD

**Issue by ekhattar** [gabriela99/capstone-code#7]
## Description

As a user on my own profile....

- when I click "edit" then change a field, for example my name from "elie" to "Elias"
- then click save
- my profile still shows the old data (e.g., "elie")
- I have to go to the user list and then go back, then I see the new data
- this impacts all changed fields: name, role, and skills

Instead, the profile should show the new data immediately after clicking "save" for better UX

**Hint:** in `ProfileActivity.java` have a good look at this line:
https://github.com/gabriela99/capstone-code/blob/796fe72e1c274edd9eb6bc059ef37f8703881b8b/app/src/main/java/com/example/capstone_code/ProfileActivity.java#L64

And read the documentation for `addValueEventListener()` vs. `addListenerForSingleValueEvent()` (which is what's currently there)

- [Firebase documentation](https://firebase.google.com/docs/database/admin/retrieve-data)

- [Stackoverflow post](https://stackoverflow.com/questions/41579000/difference-between-addvalueeventlistener-and-addlistenerforsinglevalueevent)

> addValueEventListener() keep listening to query or database reference it is attached to.
> 
> But addListenerForSingleValueEvent() executes onDataChange method immediately and after executing that method once, it stops listening to the reference location it is attached to.

**Comment by gabriela99** [comment]
https://github.com/gabriela99/capstone-code/blob/796fe72e1c274edd9eb6bc059ef37f8703881b8b/app/src/main/java/com/example/capstone_code/ProfileActivity.java#L64

This line has been updated to include `addValueEventListener()`
